name: aoc
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  html: ^0.15.4
  http: ^1.1.2
  meta: ^1.11.0
  quiver: ^3.2.1

dev_dependencies:
  fd_lints: ^2.2.0
  test: ^1.24.9
